import LocalStore from "../plugins/LocalStore";
import axios from 'axios';

export default {

    state: {
        user: [],
        // menu:  [{"main_menu_id":"1","main_menu_name":"Home","active_yn":"Y","sl_no":"1","menu_url":"\/home","menu_icon":"bx-home","visible_yn":"N","childs":[]},{"main_menu_id":"2","main_menu_name":"Setup","active_yn":"Y","sl_no":"2","menu_url":"#","menu_icon":"bx-cog","visible_yn":"N","childs":[{"menu_id":"2006","menu_name":"Vehicle Class Mapping","main_menu_id":"2","menu_url":"\/class-wise-item-mapping","permission_wise_yn":"N","active_yn":"Y","sl_no":"6","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2007","menu_name":"Lane Type Mapping","main_menu_id":"2","menu_url":"\/lane-type-mapping","permission_wise_yn":"N","active_yn":"Y","sl_no":"10","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2008","menu_name":"Sub Test Type","main_menu_id":"2","menu_url":"\/sub-test-type","permission_wise_yn":"N","active_yn":"Y","sl_no":"11","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2001","menu_name":"Center","main_menu_id":"2","menu_url":"\/center","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2002","menu_name":"Booth","main_menu_id":"2","menu_url":"\/booth","permission_wise_yn":"N","active_yn":"Y","sl_no":"2","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2003","menu_name":"Lane","main_menu_id":"2","menu_url":"\/lane","permission_wise_yn":"N","active_yn":"Y","sl_no":"3","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"2004","menu_name":"Device","main_menu_id":"2","menu_url":"\/device-setup","permission_wise_yn":"N","active_yn":"Y","sl_no":"4","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]},{"main_menu_id":"3","main_menu_name":"User Management","active_yn":"Y","sl_no":"3","menu_url":"#","menu_icon":"bxs-user-detail","visible_yn":"N","childs":[{"menu_id":"3002","menu_name":"Users","main_menu_id":"3","menu_url":"\/users","permission_wise_yn":"N","active_yn":"Y","sl_no":"2","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"3003","menu_name":"Shifting","main_menu_id":"3","menu_url":"\/shift-management","permission_wise_yn":"N","active_yn":"Y","sl_no":"3","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"3001","menu_name":"Roles","main_menu_id":"3","menu_url":"\/roles","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]},{"main_menu_id":"4","main_menu_name":"Inspection","active_yn":"Y","sl_no":"4","menu_url":"#","menu_icon":"bx-bookmark-plus","visible_yn":"N","childs":[{"menu_id":"4002","menu_name":"Check Appointment","main_menu_id":"4","menu_url":"\/check-appointment","permission_wise_yn":"N","active_yn":"Y","sl_no":"2","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"4003","menu_name":"Results Publishing","main_menu_id":"4","menu_url":"\/results","permission_wise_yn":"N","active_yn":"Y","sl_no":"3","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"4004","menu_name":"Certification","main_menu_id":"4","menu_url":"\/certificates","permission_wise_yn":"N","active_yn":"Y","sl_no":"4","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"4005","menu_name":"Queue Cancellation","main_menu_id":"4","menu_url":"\/queue-cancel","permission_wise_yn":"N","active_yn":"Y","sl_no":"5","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"4001","menu_name":"New Appointment","main_menu_id":"4","menu_url":"\/new-appointment","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]},{"main_menu_id":"5","main_menu_name":"Inventory","active_yn":"Y","sl_no":"5","menu_url":"#","menu_icon":"bx-detail","visible_yn":"N","childs":[{"menu_id":"5001","menu_name":"Inventory Receive","main_menu_id":"5","menu_url":"\/inventory","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"5002","menu_name":"Skip Page","main_menu_id":"5","menu_url":"\/pad","permission_wise_yn":"N","active_yn":"Y","sl_no":"2","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]},{"main_menu_id":"6","main_menu_name":"Reports","active_yn":"Y","sl_no":"6","menu_url":"#","menu_icon":"bx-detail","visible_yn":"N","childs":[{"menu_id":"6001","menu_name":"Report-1","main_menu_id":"6","menu_url":"#","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]},{"main_menu_id":"7","main_menu_name":"Logs","active_yn":"Y","sl_no":"7","menu_url":"#","menu_icon":"bx-paint-roll","visible_yn":"N","childs":[{"menu_id":"7001","menu_name":"API Log","main_menu_id":"7","menu_url":"\/api-access-log","permission_wise_yn":"N","active_yn":"Y","sl_no":"1","menu_icon":"bx-subdirectory-right","visible_yn":"N"},{"menu_id":"7002","menu_name":"Activity Log","main_menu_id":"7","menu_url":"\/activity-log","permission_wise_yn":"N","active_yn":"Y","sl_no":"2","menu_icon":"bx-subdirectory-right","visible_yn":"N"}]}]

        menu:[
            {
                "main_menu_id": "1",
                "main_menu_name": "Home",
                "main_menu_status": "Y",
                "main_menu_url": "/avis/home",
                "main_menu_component_name": null,
                "main_menu_visibility": "N",
                "main_menu_sl_no": "1",
                "main_menu_icon": "bx-home",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#1",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": []
            },
            {
                "main_menu_id": "2",
                "main_menu_name": "Setup",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "Y",
                "main_menu_sl_no": "2",
                "main_menu_icon": "bx-cog",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#2",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": [
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2001",
                        "menu_name": "Center",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/center",
                        "menu_component_name": "CenterPage",
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2002",
                        "menu_name": "Booth",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/booth",
                        "menu_component_name": "BoothPage",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2003",
                        "menu_name": "Lane",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/lane",
                        "menu_component_name": "LanePage",
                        "menu_sl_no": "3",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2004",
                        "menu_name": "Device",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/device-setup",
                        "menu_component_name": "DeviceSetupPAge",
                        "menu_sl_no": "4",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2005",
                        "menu_name": "Shift",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/shift-setup",
                        "menu_component_name": "ShiftSetupPAge",
                        "menu_sl_no": "5",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2006",
                        "menu_name": "Vehicle Class Mapping",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/class-wise-item-mapping",
                        "menu_component_name": 'ClassMappingPage',
                        "menu_sl_no": "6",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2007",
                        "menu_name": "Lane Type Mapping",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/lane-type-mapping",
                        "menu_component_name": "LaneTypeMapping",
                        "menu_sl_no": "10",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2008",
                        "menu_name": "Sub Test Type",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/sub-test-type",
                        "menu_component_name": "SubTestTypePage",
                        "menu_sl_no": "11",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2009",
                        "menu_name": "User Type Roles",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/user-type-role-mapping",
                        "menu_component_name": "UserTypeRoleMappingPage",
                        "menu_sl_no": "12",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2014",
                        "menu_name": "Workflow",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/workflow",
                        "menu_component_name": "WorkflowPage",
                        "menu_sl_no": "204",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                    },
                    {
                        "main_menu_id": "2",
                        "main_menu_name": "Setup",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "2",
                        "main_menu_icon": "bx-cog",
                        "menu_id": "2015",
                        "menu_name": "General & Schedule Setting",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/schedule-task-setup",
                        "menu_component_name": "ScheduleTaskSetup",
                        "menu_sl_no": "205",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                    }
                ]
            },
            {
                "main_menu_id": "3",
                "main_menu_name": "User Management",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "Y",
                "main_menu_sl_no": "3",
                "main_menu_icon": "bxs-user-detail",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#3",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": [
                    {
                        "main_menu_id": "3",
                        "main_menu_name": "User Management",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "3",
                        "main_menu_icon": "bxs-user-detail",
                        "menu_id": "3001",
                        "menu_name": "Roles",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/roles",
                        "menu_component_name": "RolePage",
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "3",
                        "main_menu_name": "User Management",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "3",
                        "main_menu_icon": "bxs-user-detail",
                        "menu_id": "3002",
                        "menu_name": "Users",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/users",
                        "menu_component_name": "UserPage",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "3",
                        "main_menu_name": "User Management",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "3",
                        "main_menu_icon": "bxs-user-detail",
                        "menu_id": "3003",
                        "menu_name": "Shifting",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/shift-management",
                        "menu_component_name": "ShiftSetupPAge",
                        "menu_sl_no": "3",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    }
                ]
            },
            {
                "main_menu_id": "4",
                "main_menu_name": "Inspection",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "Y",
                "main_menu_sl_no": "4",
                "main_menu_icon": "bx-bookmark-plus",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#4",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": [
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4001",
                        "menu_name": "New Appointment",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/new-appointment",
                        "menu_component_name": null,
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": "3",
                        "role_name": "FRONT DESK",
                        "role_status": "Y",
                        "user_type_role_status": "Y",
                        "user_type_id": "4",
                        "role_main_menu": "4",
                        "role_menu_id": "4001",
                        "role_menu_status": "Y",
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4002",
                        "menu_name": "Check Appointment",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/check-appointment",
                        "menu_component_name": "CheckAppointmentPage",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": "3",
                        "role_name": "FRONT DESK",
                        "role_status": "Y",
                        "user_type_role_status": "Y",
                        "user_type_id": "4",
                        "role_main_menu": "4",
                        "role_menu_id": "4002",
                        "role_menu_status": "Y",
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4003",
                        "menu_name": "Results Publishing",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/results",
                        "menu_component_name": null,
                        "menu_sl_no": "3",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": "4",
                        "role_name": "RESULT PUBLISHER",
                        "role_status": "Y",
                        "user_type_role_status": "Y",
                        "user_type_id": "4",
                        "role_main_menu": "4",
                        "role_menu_id": "4003",
                        "role_menu_status": "Y",
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4004",
                        "menu_name": "Certification",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/certificates",
                        "menu_component_name": "CertificatePage",
                        "menu_sl_no": "4",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4005",
                        "menu_name": "Queue Cancellation",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/queue-cancel",
                        "menu_component_name": "QueueCancel",
                        "menu_sl_no": "5",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "4",
                        "main_menu_name": "Inspection",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "4",
                        "main_menu_icon": "bx-bookmark-plus",
                        "menu_id": "4006",
                        "menu_name": "Inspection Timeline",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/steps-timeline",
                        "menu_component_name": "StepsTimeLine",
                        "menu_sl_no": "6",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    }
                ]
            },
            {
                "main_menu_id": "5",
                "main_menu_name": "Inventory",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "Y",
                "main_menu_sl_no": "5",
                "main_menu_icon": "bx-detail",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#5",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": [
                    {
                        "main_menu_id": "5",
                        "main_menu_name": "Inventory",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "5",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "5001",
                        "menu_name": "Inventory Receive",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/inventory",
                        "menu_component_name": "InventoryPage",
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "5",
                        "main_menu_name": "Inventory",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "5",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "5002",
                        "menu_name": "Skip Page",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/pad",
                        "menu_component_name": "PadPage",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    }
                ]
            },
            {
                "main_menu_id": "6",
                "main_menu_name": "Reports",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "Y",
                "main_menu_sl_no": "6",
                "main_menu_icon": "bx-detail",
                "menu_id": null,
                "menu_name": "N",
                "menu_status": "N",
                "menu_visibility": "N",
                "part_menu_yn": "N",
                "menu_url": "/#6",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "permission": true,
                "childs": [
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6001",
                        "menu_name": "Result Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-result",
                        "menu_component_name": "ReportResult",
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": true,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6002",
                        "menu_name": "Inventory Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-inventory",
                        "menu_component_name": "ReportInventory",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": "Y",
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6003",
                        "menu_name": "Stage Wise Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-stage",
                        "menu_component_name": "ReportStage",
                        "menu_sl_no": "3",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6004",
                        "menu_name": "Shift Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-shifting",
                        "menu_component_name": "ReportShift",
                        "menu_sl_no": "4",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6005",
                        "menu_name": "Certificate Count Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-certificate-count",
                        "menu_component_name": "ReportCertificateCount",
                        "menu_sl_no": "5",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6005",
                        "menu_name": "Certificate Rating Report",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-customer-rating",
                        "menu_component_name": "ReportRating",
                        "menu_sl_no": "5",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                    {
                        "main_menu_id": "6",
                        "main_menu_name": "Reports",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "Y",
                        "main_menu_sl_no": "6",
                        "main_menu_icon": "bx-detail",
                        "menu_id": "6005",
                        "menu_name": "Certificate Rating Summery",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/report-customer-rating-summary",
                        "menu_component_name": "ReportRatingSummary",
                        "menu_sl_no": "5",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null,
                        "permission": false,
                        "childs": []
                    },
                ]
            },
            {
                "main_menu_id": "7",
                "main_menu_name": "Logs",
                "main_menu_status": "Y",
                "main_menu_url": "#",
                "main_menu_component_name": null,
                "main_menu_visibility": "N",
                "main_menu_sl_no": "7",
                "main_menu_icon": "bx-paint-roll",
                "menu_id": null,
                "menu_name": null,
                "menu_status": null,
                "menu_visibility": null,
                "part_menu_yn": null,
                "menu_url": "/#7",
                "menu_component_name": null,
                "menu_sl_no": "0",
                "menu_icon": null,
                "menu_type": "PARENT",
                "role_id": null,
                "role_name": null,
                "role_status": null,
                "user_type_role_status": null,
                "user_type_id": null,
                "role_main_menu": null,
                "role_menu_id": null,
                "role_menu_status": null,
                "user_menu_insert_status": null,
                "user_menu_edit_status": null,
                "user_menu_delete_status": null,
                "childs": [
                    {
                        "main_menu_id": "7",
                        "main_menu_name": "Logs",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "N",
                        "main_menu_sl_no": "7",
                        "main_menu_icon": "bx-paint-roll",
                        "menu_id": "7001",
                        "menu_name": "API Log",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/url-access-log",
                        "menu_component_name": "ApiAccessLogPage",
                        "menu_sl_no": "1",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    },
                    {
                        "main_menu_id": "7",
                        "main_menu_name": "Logs",
                        "main_menu_status": "Y",
                        "main_menu_url": "#",
                        "main_menu_component_name": null,
                        "main_menu_visibility": "N",
                        "main_menu_sl_no": "7",
                        "main_menu_icon": "bx-paint-roll",
                        "menu_id": "7002",
                        "menu_name": "Activity Log",
                        "menu_status": "Y",
                        "menu_visibility": "Y",
                        "part_menu_yn": "N",
                        "menu_url": "/activity-log",
                        "menu_component_name": "ActivityLogPage",
                        "menu_sl_no": "2",
                        "menu_icon": "bx-subdirectory-right",
                        "menu_type": "CHILD",
                        "role_id": null,
                        "role_name": null,
                        "role_status": null,
                        "user_type_role_status": null,
                        "user_type_id": null,
                        "role_main_menu": null,
                        "role_menu_id": null,
                        "role_menu_status": null,
                        "user_menu_insert_status": null,
                        "user_menu_edit_status": null,
                        "user_menu_delete_status": null
                    }
                ]
            },
            {
                "main_menu_id":"8",
                "main_menu_name":"Workflow",
                "main_menu_status":"Y",
                "main_menu_url":"#",
                "main_menu_component_name":null,
                "main_menu_visibility":"Y",
                "main_menu_sl_no":"8",
                "main_menu_icon":"bx-detail",
                "menu_id":null,
                "menu_name":"N",
                "menu_status":"N",
                "menu_visibility":"N",
                "part_menu_yn":"N",
                "menu_url":"/#8",
                "menu_component_name":null,
                "menu_sl_no":"0",
                "menu_icon":null,
                "menu_type":"PARENT",
                "role_id":null,
                "role_name":null,
                "role_status":null,
                "user_type_role_status":null,
                "user_type_id":null,
                "role_main_menu":null,
                "role_menu_id":null,
                "role_menu_status":null,
                "user_menu_insert_status":null,
                "user_menu_edit_status":null,
                "user_menu_delete_status":null,
                "permission":true,
                "childs":[
                    {
                        "main_menu_id":"8",
                        "main_menu_name":"Workflow",
                        "main_menu_status":"Y",
                        "main_menu_url":"#",
                        "main_menu_component_name":null,
                        "main_menu_visibility":"Y",
                        "main_menu_sl_no":"8",
                        "main_menu_icon":"bx-detail",
                        "menu_id":"8001",
                        "menu_name":"Dashboard",
                        "menu_status":"Y",
                        "menu_visibility":"Y",
                        "part_menu_yn":"N",
                        "menu_url":"/workflow-dashboard",
                        "menu_component_name":"WorkflowDashboard",
                        "menu_sl_no":"1",
                        "menu_icon":"bx-subdirectory-right",
                        "menu_type":"CHILD",
                        "role_id":null,
                        "role_name":null,
                        "role_status":null,
                        "user_type_role_status":null,
                        "user_type_id":null,
                        "role_main_menu":null,
                        "role_menu_id":null,
                        "role_menu_status":null,
                        "user_menu_insert_status":null,
                        "user_menu_edit_status":null,
                        "user_menu_delete_status":null,
                        "permission":false,
                        "childs":[

                        ]
                    }
                ]
            }
        ],
        notifications:[],
    },
    getters: {
        getUser(state){ //take parameter state
            if(state.user.length> 0){
                return (state.user)??state.user;
            }else {
                return  LocalStore.getStorage('user');
            }
        },
        getMenu(state){
            if(state.menu.length> 0){
                return (state.menu)??state.menu;
            }else {
                return  LocalStore.getStorage('menu');
            }
        },
        getNotifications(state){
            if(state.notifications.length > 0)
            {
                return (state.notifications)??state.notifications;
            }else{
               return LocalStore.getStorage('notifications');
            }

        },
        getToken(state){
            if(state.token>=0){
                return (state.token)??state.token;
            }else{
                return LocalStore.getStorage('token');
            }    
        },
        // getRerefreshToken(state){
        //     if(state.refresh_token>0){
        //         return(state.refresh_token)??state.refresh_token;
        //     }else{
        //     return LocalStore.getStorage('refresh_token');}
        // }

    },

    actions: {
        setUser(context){
            var userData = LocalStore.getStorage('user');
            context.commit("user",userData) //user will be run from mutation
        },
        removeUser(context){
            context.commit("user",false) //user will be run from mutation
        },
        setMenu(context){ //call this.$store.dispatch("setMenu");
            axios
                .get(process.env.MIX_API_URL + '/access/menus/', {})
                .then(response => {
                    var menuData = (response.data.status)?response.data.data:[];
                    LocalStore.setStorage('menu', menuData);
                    context.commit("menu",menuData);
                })
                .catch(error => {
                    LocalStore.setStorage('menu', []);
                    context.commit("menu",[]);
                })
                .finally(() => {
                });
        },
        removeMenu(context){  //call this.$store.dispatch("removeMenu");
            context.commit("menu",[]) //user will be run from mutation
        },
        setNotifications(context){
            let res = LocalStore.getStorage('user');
            if(res){
                axios
                    .get(process.env.MIX_API_URL + '/workflow/notifications', {})
                    .then(response => {
                        if(response.data.status){
                            let notifications  = response.data.data;
                            LocalStore.setStorage('notifications',response.data.data);
                            context.commit("notifications",notifications);
                        }

                    })
                    .catch(error => {
                        LocalStore.setStorage('notifications',[])
                        context.commit("notifications",[]);
                    })
                    .finally(() => {
                    });
            }
        },
        removeNotifications(){
            context.commit("notifications",[]);
        }

    },

    mutations: {
        user(state,data) {
            return state.user = data
        },
        menu(state,data) {
            return state.menu = data
        },
        notifications(state,data){
            return state.notifications = data;
        }
    }

}
